export const GET_FORMS = "GET_FORMS";
export const GET_FORMS_SUCCESS = "GET_FORMS_SUCCESS";
export const GET_FORMS_FAIL = "GET_FORMS_FAIL";

export const GET_FORM = "GET_FORM";
export const GET_FORM_SUCCESS = "GET_FORM_SUCCESS";
export const GET_FORM_FAIL = "GET_FORM_FAIL";

export const ADD_FORM = "ADD_FORM";
export const ADD_FORM_SUCCESS = "ADD_FORM_SUCCESS";
export const ADD_FORM_FAIL = "ADD_FORM_FAIL";

export const SAVE_FORM_RESPONSE = "SAVE_FORM_RESPONSE";
export const SAVE_FORM_RESPONSE_SUCCESS = "SAVE_FORM_RESPONSE_SUCCESS";
export const SAVE_FORM_RESPONSE_FAIL = "SAVE_FORM_RESPONSE_FAIL";